---
# Add Title Message & or ยง for color
Main:
  Title: "Select"
  Content: "Text here"
  Exit-Button: "Exit The Main Menu"
##########################################################
#
# Repair System (1)
#
#
Repair:
  ShowMyMoney: "Your money: "
  Cost: "100"
  Title: "Repair form"
  Content: "text here"
  Button: "Tap to repair"
  Back: "Go Back to Main Menu"
  Repair-Message: "Repair"
  NoMoney: "[!] You need "
  HoldItem: "[!] Hold item in hand"
  succesfully: "[!] You succesfully repaired your item"
##########################################################
#
# Rename System (2)
#
Rename:
  ShowMyMoney: "Your money: "
  Cost: "100"
  Title: "You rename: "
  Content: "Renaming cost: "
Rename-Message:
  NoMoney: "[!] You have enought money. You need"
  HoldItem: "[!] Hold item in hand"
  succesfully: "[!] Item renamed in "
...
